- id: code-checker
  name: Code-Checker
  entry: code-checker
  language: python
- id: merged-code-checker
  name: Merged-Code-Checker
  entry: merged-code-checker
  language: python
- id: batch-yaml-sorter
  name: Batch-Yaml-Sorter
  entry: batch-yaml-sorter
  language: python
- id: batch-yaml-checker
  name: Batch-Yaml-Checker
  entry: batch-yaml-checker
  language: python
- id: merge-branch-checker
  name: Merge-Branch-Checker
  entry: merge-branch-checker
  language: python
- id: pr-status-checker
  name: Pr-Status-Checker
  entry: pr-status-checker
  language: python
