- id: code-checker
  name: Code-Checker
  description: check python code
  entry: code-checker
  language: python
- id: batch-yaml-checker
  name: Batch-Yaml-Checker
  description: check batch yaml
  entry: batch-yaml-checker
  language: python