- id: code-checker
  name: Code-Checker
  description: check python code
  entry: code-checker
  language: python
- id: batch-yaml-sorter
  name: Batch-Yaml-Sorter
  description: sort batch yaml
  entry: batch-yaml-sorter
  language: python
- id: batch-yaml-checker
  name: Batch-Yaml-Checker
  description: check batch yaml
  entry: batch-yaml-checker
  language: python
- id: todo-checker
  name: Todo-Checker
  description: check todo comments
  entry: todo-checker
  language: python